export const ROUTES = {
  HOME: "/home",
  AUTH: "/auth",
  REGISTER: "/auth/register",
  LOGIN: "/auth/login",
  MENU: "/menu",
  CART: "/cart",
  RESTAURANT: "/restaurant/:id",
  SEARCH: "/search/:selectedCity/:searchValue",
  PRODUCT: "/product/:id",
  USER: "/user",
  CHECKOUT: "/checkout",
  PAYMENT_SUCCESS: "/payment-success",
  PAYMENT_FAILED: "/payment-failed",
  NOT_FOUND: "*",
};
